version: '3.8'
services:
  db:
    image: postgres:17
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stonkerino
    networks:
      - my_app
    volumes:
      - ./data/docker/db-logger/pgdata/data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack
    ports:
      - '36432:6379'
    networks:
      - my_app
    command: [sh, -c, 'rm -f /data/dump.rdb && redis-server --protected-mode no  --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so']
networks:
  my_app: